import Heil5.Basic
import Heil5.Defs
import Heil5.Ident
import Heil5.Golden
import Heil5.Compose
import Heil5.Inside
import Heil5.Radon
import Heil5.Pentagon
import Heil5.Collinear
import Heil5.AnyTriple
import Heil5.ConvexPos5
import Heil5.Main
import Heil5.Bridge
import Heil5.Rigid
import Heil5.Structure
