import Heil7.Hull6OneNegativeData

/-!
# Exact certificate for the one-negative H6 scalar inequality

This is the kernel-checked semantic bridge for the 924-entry fallback
certificate generated by `support/h6_one_negative_bernstein.py`.

The cleared numerator is kept in its short factored form.  Fourteen `ring`
identities check the generated rational tables: the three Bernstein layers in
the interval parameter use triangular subdivision orders 3, 2, and 1.  The
remaining theorems route an arbitrary point of `p,t >= 0, p+t <= 3` to the
appropriate cell and combine the three positive layers.
-/

set_option linter.style.header false

namespace HeilbronnChallenge.N7Upper

/-- The exact polynomial `-(w*d)^2*G0`, constructed without division.

Here `s = h + z*(smax-h)`, with `R=1/w`, `h=2/d`, and
`smax=3-p-t-R`.  The factored construction is the authoritative counterpart
of `build_numerator` in the generator. -/
def h6OneNegativeNumerator (p t z : ℝ) : ℝ :=
  let w := 4 - p - t
  let d := 3 + 4 * p - p ^ 2
  let wd := w * d
  let B := p + t + p * t - 1
  let spanNum := (w - 1) * wd - d - 2 * w
  let sNum := 2 * w + z * spanNum
  let lNum := (w ^ 2 - 1) * d - sNum
  let dNum := B * ((1 + t) * wd + sNum) + t * wd
  let cNum := (2 + p) * w + (1 + p)
  (1 + t) * cNum * w * d ^ 2 - lNum * dNum

/-- The three degree-two Bernstein layers in `z`. -/
def h6OneNegativeLayer0 (p t : ℝ) : ℝ :=
  h6OneNegativeNumerator p t 0

noncomputable def h6OneNegativeLayer1 (p t : ℝ) : ℝ :=
  2 * h6OneNegativeNumerator p t (1 / 2) -
    (h6OneNegativeNumerator p t 0 + h6OneNegativeNumerator p t 1) / 2

def h6OneNegativeLayer2 (p t : ℝ) : ℝ :=
  h6OneNegativeNumerator p t 1

theorem h6OneNegativeNumerator_layers (p t z : ℝ) :
    h6OneNegativeNumerator p t z =
      h6OneNegativeLayer0 p t * (1 - z) ^ 2 +
      2 * h6OneNegativeLayer1 p t * z * (1 - z) +
      h6OneNegativeLayer2 p t * z ^ 2 := by
  simp only [h6OneNegativeLayer0, h6OneNegativeLayer1,
    h6OneNegativeLayer2, h6OneNegativeNumerator]
  ring

private lemma certified_cell_pos
    (cell : Fin 14) (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < tri10Bernstein
      (fun k => (h6OneNegativeBernsteinData cell k : ℝ)) u v := by
  exact tri10Bernstein_rat_pos
    (h6OneNegativeBernsteinData cell)
    (h6OneNegativeBernsteinMin cell) u v
    (h6OneNegativeBernsteinMin_pos cell)
    (h6OneNegativeBernsteinData_lower cell) hu hv huv

/-! ## Layer zero: the order-three triangular grid -/

set_option maxHeartbeats 2000000 in
private lemma layer0_U00_repr (u v : ℝ) :
    h6OneNegativeLayer0 u v =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 0 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_U01_repr (u v : ℝ) :
    h6OneNegativeLayer0 u (1 + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 1 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_U02_repr (u v : ℝ) :
    h6OneNegativeLayer0 u (2 + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 2 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_U10_repr (u v : ℝ) :
    h6OneNegativeLayer0 (1 + u) v =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 3 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_U11_repr (u v : ℝ) :
    h6OneNegativeLayer0 (1 + u) (1 + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 4 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_U20_repr (u v : ℝ) :
    h6OneNegativeLayer0 (2 + u) v =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 5 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_D00_repr (u v : ℝ) :
    h6OneNegativeLayer0 (1 - v) (u + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 6 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_D01_repr (u v : ℝ) :
    h6OneNegativeLayer0 (1 - v) (1 + u + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 7 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer0_D10_repr (u v : ℝ) :
    h6OneNegativeLayer0 (2 - v) (u + v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 8 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer0, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

private lemma layer0_U00_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 u v := by
  rw [layer0_U00_repr]
  exact certified_cell_pos 0 u v hu hv huv

private lemma layer0_U01_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 u (1 + v) := by
  rw [layer0_U01_repr]
  exact certified_cell_pos 1 u v hu hv huv

private lemma layer0_U02_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 u (2 + v) := by
  rw [layer0_U02_repr]
  exact certified_cell_pos 2 u v hu hv huv

private lemma layer0_U10_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (1 + u) v := by
  rw [layer0_U10_repr]
  exact certified_cell_pos 3 u v hu hv huv

private lemma layer0_U11_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (1 + u) (1 + v) := by
  rw [layer0_U11_repr]
  exact certified_cell_pos 4 u v hu hv huv

private lemma layer0_U20_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (2 + u) v := by
  rw [layer0_U20_repr]
  exact certified_cell_pos 5 u v hu hv huv

private lemma layer0_D00_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (1 - v) (u + v) := by
  rw [layer0_D00_repr]
  exact certified_cell_pos 6 u v hu hv huv

private lemma layer0_D01_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (1 - v) (1 + u + v) := by
  rw [layer0_D01_repr]
  exact certified_cell_pos 7 u v hu hv huv

private lemma layer0_D10_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer0 (2 - v) (u + v) := by
  rw [layer0_D10_repr]
  exact certified_cell_pos 8 u v hu hv huv

theorem h6OneNegativeLayer0_pos
    {p t : ℝ} (hp : 0 ≤ p) (ht : 0 ≤ t) (hsum : p + t ≤ 3) :
    0 < h6OneNegativeLayer0 p t := by
  by_cases hp1 : p ≤ 1
  · by_cases ht1 : t ≤ 1
    · by_cases hs1 : p + t ≤ 1
      · exact layer0_U00_pos p t hp ht hs1
      · let u := p + t - 1
        let v := 1 - p
        have hu : 0 ≤ u := by simp only [u]; linarith
        have hv : 0 ≤ v := by simp only [v]; linarith
        have huv : u + v ≤ 1 := by simp only [u, v]; linarith
        convert layer0_D00_pos u v hu hv huv using 1 <;>
          simp only [u, v] <;> ring
    · by_cases ht2 : t ≤ 2
      · by_cases hs2 : p + t ≤ 2
        · let u := p
          let v := t - 1
          have hu : 0 ≤ u := hp
          have hv : 0 ≤ v := by simp only [v]; linarith
          have huv : u + v ≤ 1 := by simp only [u, v]; linarith
          convert layer0_U01_pos u v hu hv huv using 1 <;>
            simp only [u, v] <;> ring
        · let u := p + t - 2
          let v := 1 - p
          have hu : 0 ≤ u := by simp only [u]; linarith
          have hv : 0 ≤ v := by simp only [v]; linarith
          have huv : u + v ≤ 1 := by simp only [u, v]; linarith
          convert layer0_D01_pos u v hu hv huv using 1 <;>
            simp only [u, v] <;> ring
      · let u := p
        let v := t - 2
        have hu : 0 ≤ u := hp
        have hv : 0 ≤ v := by simp only [v]; linarith
        have huv : u + v ≤ 1 := by simp only [u, v]; linarith
        convert layer0_U02_pos u v hu hv huv using 1 <;>
          simp only [u, v] <;> ring
  · by_cases hp2 : p ≤ 2
    · by_cases ht1 : t ≤ 1
      · by_cases hs2 : p + t ≤ 2
        · let u := p - 1
          let v := t
          have hu : 0 ≤ u := by simp only [u]; linarith
          have hv : 0 ≤ v := ht
          have huv : u + v ≤ 1 := by simp only [u, v]; linarith
          convert layer0_U10_pos u v hu hv huv using 1 <;>
            simp only [u, v] <;> ring
        · let u := p + t - 2
          let v := 2 - p
          have hu : 0 ≤ u := by simp only [u]; linarith
          have hv : 0 ≤ v := by simp only [v]; linarith
          have huv : u + v ≤ 1 := by simp only [u, v]; linarith
          convert layer0_D10_pos u v hu hv huv using 1 <;>
            simp only [u, v] <;> ring
      · let u := p - 1
        let v := t - 1
        have hu : 0 ≤ u := by simp only [u]; linarith
        have hv : 0 ≤ v := by simp only [v]; linarith
        have huv : u + v ≤ 1 := by simp only [u, v]; linarith
        convert layer0_U11_pos u v hu hv huv using 1 <;>
          simp only [u, v] <;> ring
    · let u := p - 2
      let v := t
      have hu : 0 ≤ u := by simp only [u]; linarith
      have hv : 0 ≤ v := ht
      have huv : u + v ≤ 1 := by simp only [u, v]; linarith
      convert layer0_U20_pos u v hu hv huv using 1 <;>
        simp only [u, v] <;> ring

/-! ## Layer one: the order-two triangular grid -/

set_option maxHeartbeats 2000000 in
private lemma layer1_U00_repr (u v : ℝ) :
    h6OneNegativeLayer1 ((3 / 2) * u) ((3 / 2) * v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 9 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer1, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer1_U01_repr (u v : ℝ) :
    h6OneNegativeLayer1 ((3 / 2) * u) ((3 / 2) * (1 + v)) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 10 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer1, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer1_U10_repr (u v : ℝ) :
    h6OneNegativeLayer1 ((3 / 2) * (1 + u)) ((3 / 2) * v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 11 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer1, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

set_option maxHeartbeats 2000000 in
private lemma layer1_D00_repr (u v : ℝ) :
    h6OneNegativeLayer1 ((3 / 2) * (1 - v))
        ((3 / 2) * (u + v)) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 12 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer1, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

private lemma layer1_U00_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer1 ((3 / 2) * u) ((3 / 2) * v) := by
  rw [layer1_U00_repr]
  exact certified_cell_pos 9 u v hu hv huv

private lemma layer1_U01_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer1 ((3 / 2) * u) ((3 / 2) * (1 + v)) := by
  rw [layer1_U01_repr]
  exact certified_cell_pos 10 u v hu hv huv

private lemma layer1_U10_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer1 ((3 / 2) * (1 + u)) ((3 / 2) * v) := by
  rw [layer1_U10_repr]
  exact certified_cell_pos 11 u v hu hv huv

private lemma layer1_D00_pos (u v : ℝ)
    (hu : 0 ≤ u) (hv : 0 ≤ v) (huv : u + v ≤ 1) :
    0 < h6OneNegativeLayer1 ((3 / 2) * (1 - v))
        ((3 / 2) * (u + v)) := by
  rw [layer1_D00_repr]
  exact certified_cell_pos 12 u v hu hv huv

theorem h6OneNegativeLayer1_pos
    {p t : ℝ} (hp : 0 ≤ p) (ht : 0 ≤ t) (hsum : p + t ≤ 3) :
    0 < h6OneNegativeLayer1 p t := by
  by_cases hp3 : p ≤ 3 / 2
  · by_cases ht3 : t ≤ 3 / 2
    · by_cases hs3 : p + t ≤ 3 / 2
      · let u := 2 * p / 3
        let v := 2 * t / 3
        have hu : 0 ≤ u := by simp only [u]; positivity
        have hv : 0 ≤ v := by simp only [v]; positivity
        have huv : u + v ≤ 1 := by simp only [u, v]; linarith
        convert layer1_U00_pos u v hu hv huv using 1 <;>
          simp only [u, v] <;> ring
      · let u := 2 * (p + t) / 3 - 1
        let v := 1 - 2 * p / 3
        have hu : 0 ≤ u := by simp only [u]; linarith
        have hv : 0 ≤ v := by simp only [v]; linarith
        have huv : u + v ≤ 1 := by simp only [u, v]; linarith
        convert layer1_D00_pos u v hu hv huv using 1 <;>
          simp only [u, v] <;> ring
    · let u := 2 * p / 3
      let v := 2 * t / 3 - 1
      have hu : 0 ≤ u := by simp only [u]; positivity
      have hv : 0 ≤ v := by simp only [v]; linarith
      have huv : u + v ≤ 1 := by simp only [u, v]; linarith
      convert layer1_U01_pos u v hu hv huv using 1 <;>
        simp only [u, v] <;> ring
  · let u := 2 * p / 3 - 1
    let v := 2 * t / 3
    have hu : 0 ≤ u := by simp only [u]; linarith
    have hv : 0 ≤ v := by simp only [v]; positivity
    have huv : u + v ≤ 1 := by simp only [u, v]; linarith
    convert layer1_U10_pos u v hu hv huv using 1 <;>
      simp only [u, v] <;> ring

/-! ## Layer two and the quadratic blend -/

set_option maxHeartbeats 2000000 in
private lemma layer2_U00_repr (u v : ℝ) :
    h6OneNegativeLayer2 (3 * u) (3 * v) =
      tri10Bernstein
        (fun k => (h6OneNegativeBernsteinData 13 k : ℝ)) u v := by
  norm_num [h6OneNegativeLayer2, h6OneNegativeNumerator,
    tri10Bernstein, h6OneNegativeBernsteinData,
    h6OneNegativeBernsteinRows]
  simp only [Matrix.cons_val]
  ring

theorem h6OneNegativeLayer2_pos
    {p t : ℝ} (hp : 0 ≤ p) (ht : 0 ≤ t) (hsum : p + t ≤ 3) :
    0 < h6OneNegativeLayer2 p t := by
  let u := p / 3
  let v := t / 3
  have hu : 0 ≤ u := by simp only [u]; positivity
  have hv : 0 ≤ v := by simp only [v]; positivity
  have huv : u + v ≤ 1 := by simp only [u, v]; linarith
  have hpos := certified_cell_pos 13 u v hu hv huv
  rw [← layer2_U00_repr] at hpos
  convert hpos using 1 <;> simp only [u, v] <;> ring

/-- Exact positivity of the cleared one-negative numerator on the whole
triangle times the closed interval. -/
theorem h6OneNegativeNumerator_pos
    {p t z : ℝ}
    (hp : 0 ≤ p) (ht : 0 ≤ t) (hsum : p + t ≤ 3)
    (hz0 : 0 ≤ z) (hz1 : z ≤ 1) :
    0 < h6OneNegativeNumerator p t z := by
  have h0 := h6OneNegativeLayer0_pos hp ht hsum
  have h1 := h6OneNegativeLayer1_pos hp ht hsum
  have h2 := h6OneNegativeLayer2_pos hp ht hsum
  have hcomp : 0 ≤ 1 - z := by linarith
  rw [h6OneNegativeNumerator_layers]
  by_cases hz : z = 0
  · simp only [hz, sub_zero, one_pow, mul_one, mul_zero, zero_mul,
      zero_pow (by decide : (2 : ℕ) ≠ 0), add_zero]
    exact h0
  · have hzpos : 0 < z := lt_of_le_of_ne hz0 (Ne.symm hz)
    have hfirst :
        0 ≤ h6OneNegativeLayer0 p t * (1 - z) ^ 2 := by positivity
    have hmiddle :
        0 ≤ 2 * h6OneNegativeLayer1 p t * z * (1 - z) := by positivity
    have hlast : 0 < h6OneNegativeLayer2 p t * z ^ 2 := by positivity
    linarith

end HeilbronnChallenge.N7Upper
