/-
Composition: the unconditional QuadHull8 theorem.
The two cross-apex identities are exact polynomial identities in
coordinates (sympy residual zero); the residual bound is discharged by
the analytic orbit-I closure.
-/
import Heilbronn8.QuadHull.Main
import Heilbronn8.QuadHull.OrbitIClosure
import Heilbronn8.TriHull.Main
import Heilbronn8.TriHull.Bridge
import Heilbronn8.Cover

namespace Heilbronn8.QuadHull

/-- A compact eight-label lookup used by geometric certificate records.
The explicit match avoids the very large dependent term generated by
eight-element vector notation. -/
@[simp] def quadLabels
    (A B C D Q P R S : Fin 8) : Fin 8 → Fin 8 :=
  fun i ↦
    match i.val with
    | 0 => A
    | 1 => B
    | 2 => C
    | 3 => D
    | 4 => Q
    | 5 => P
    | 6 => R
    | _ => S

theorem crossApexIdentity47_holds : CrossApexIdentity47 := by
  intro P A C D R
  simp only [oarea, sig]
  ring

theorem crossApexIdentity48_holds : CrossApexIdentity48 := by
  intro P A C D R
  simp only [oarea, sig]
  ring

theorem quadHull8_unconditional
    (v : Fin 8 → Point) (A B C D : Fin 8)
    (hunit : quadHullArea (v A) (v B) (v C) (v D) = 1)
    (hcert : OrbitCertificate v A B C D) :
    minTri v / 2 ≤ (5 : ℝ) / 63 :=
  quadHull8 crossApexIdentity47_holds crossApexIdentity48_holds
    orbitI_residual_bound v A B C D hunit hcert

/--
Geometric data for the balanced `2+2` diagonal branch.  The diagonal is
`BD`: `P,Q` lie in `BCD`, while `R,S` lie in `BDA`.  The two injectivity
fields are the only label bookkeeping required by the normalized
five-point triangle estimate.
-/
structure BalancedDiagonalCertificate
    (v : Fin 8 → Point) (A B C D : Fin 8) where
  P : Fin 8
  Q : Fin 8
  R : Fin 8
  S : Fin 8
  left_injective : Function.Injective ![B, C, D, P, Q]
  right_injective : Function.Injective ![B, D, A, R, S]
  BCD_pos : 0 < sig (v B) (v C) (v D)
  P_in_BCD : TriHull.InTriStrict (v P) (v B) (v C) (v D)
  Q_in_BCD : TriHull.InTriStrict (v Q) (v B) (v C) (v D)
  BDA_pos : 0 < sig (v B) (v D) (v A)
  R_in_BDA : TriHull.InTriStrict (v R) (v B) (v D) (v A)
  S_in_BDA : TriHull.InTriStrict (v S) (v B) (v D) (v A)

/--
The balanced diagonal is an honest bridge into the pre-existing orbit
interface.  Its two normalized triangle areas both exceed `F2`, so it
constructs the `NormalizedOrbitCase.balanced` constructor rather than taking
an `OrbitCertificate` as generated proof data.
-/
theorem BalancedDiagonalCertificate.orbitCertificate
    {v : Fin 8 → Point} {A B C D : Fin 8}
    (h : BalancedDiagonalCertificate v A B C D) :
    OrbitCertificate v A B C D := by
  by_cases hmzero : minTri v = 0
  · exact Or.inl hmzero
  · have hm : 0 < minTri v :=
      lt_of_le_of_ne (minTri_nonneg v) (Ne.symm hmzero)
    let L : ℝ := sig (v B) (v C) (v D) / minTri v
    let R : ℝ := sig (v B) (v D) (v A) / minTri v
    let H : ℝ := L + R
    have hLmain : 4 + 2 * Real.sqrt 3 ≤ L := by
      simpa [L] using
        TriHull.twoPointTriangle_normalized_lower_bound v
          ![B, C, D, h.P, h.Q] h.left_injective hm
          h.BCD_pos h.P_in_BCD h.Q_in_BCD
    have hRmain : 4 + 2 * Real.sqrt 3 ≤ R := by
      simpa [R] using
        TriHull.twoPointTriangle_normalized_lower_bound v
          ![B, D, A, h.R, h.S] h.right_injective hm
          h.BDA_pos h.R_in_BDA h.S_in_BDA
    have hL : F2 < L := by
      norm_num [F2] at ⊢
      nlinarith [TriHull.sixty_nine_fortieths_lt_sqrt_three]
    have hR : F2 < R := by
      norm_num [F2] at ⊢
      nlinarith [TriHull.sixty_nine_fortieths_lt_sqrt_three]
    refine Or.inr ⟨H, ?_, .balanced L R rfl hL hR⟩
    dsimp [H, L, R, quadHullArea, oarea]
    field_simp [ne_of_gt hm]
    simp only [sig]
    ring

/--
Geometric data for orbit II with secondary split `j = 2`.

The point `Q` lies in the `BCO` sector, expressed without naming the
intersection of the diagonals by membership in both `ABC` and `BCD`.
The points `P,R` lie in `QAB`, while the remaining point `Z` lies in `QDA`.
-/
structure OrbitIIJ2GeometryCertificate
    (v : Fin 8 → Point) (A B C D : Fin 8) where
  Q : Fin 8
  P : Fin 8
  R : Fin 8
  Z : Fin 8
  labels_injective : Function.Injective (quadLabels A B C D Q P R Z)
  ccw : CCWQuad (v A) (v B) (v C) (v D)
  Q_in_ABC : TriHull.InTriStrict (v Q) (v A) (v B) (v C)
  Q_in_BCD : TriHull.InTriStrict (v Q) (v B) (v C) (v D)
  P_in_QAB : TriHull.InTriStrict (v P) (v Q) (v A) (v B)
  R_in_QAB : TriHull.InTriStrict (v R) (v Q) (v A) (v B)
  Z_in_QDA : TriHull.InTriStrict (v Z) (v Q) (v D) (v A)

/--
The geometric orbit-II/`j = 2` placement constructs the direct signed-area
orbit certificate.  All scalar cells are normalized by `minTri v`; this is
the same as dividing ordinary area by `minTri v / 2`.
-/
theorem OrbitIIJ2GeometryCertificate.orbitCertificate
    {v : Fin 8 → Point} {A B C D : Fin 8}
    (h : OrbitIIJ2GeometryCertificate v A B C D) :
    OrbitCertificate v A B C D := by
  by_cases hmzero : minTri v = 0
  · exact Or.inl hmzero
  · have hm : 0 < minTri v :=
      lt_of_le_of_ne (minTri_nonneg v) (Ne.symm hmzero)
    let labels : Fin 8 → Fin 8 :=
      quadLabels A B C D h.Q h.P h.R h.Z
    have hlabels : Function.Injective labels := by
      simpa [labels] using h.labels_injective
    have unit_of_pos (i j k : Fin 8)
        (hij : i ≠ j) (hik : i ≠ k) (hjk : j ≠ k)
        (hpos : 0 < sig (v (labels i)) (v (labels j)) (v (labels k))) :
        1 ≤ sig (v (labels i)) (v (labels j)) (v (labels k)) / minTri v := by
      have hmin := minTri_le_abs_sig_of_pairwise_ne v
        (hlabels.ne hij) (hlabels.ne hik) (hlabels.ne hjk)
      rw [abs_of_pos hpos] at hmin
      rw [le_div_iff₀ hm]
      simpa using hmin
    have abs_unit (i j k : Fin 8)
        (hij : i ≠ j) (hik : i ≠ k) (hjk : j ≠ k) :
        1 ≤ |sig (v (labels i)) (v (labels j)) (v (labels k)) /
          minTri v| := by
      have hmin := minTri_le_abs_sig_of_pairwise_ne v
        (hlabels.ne hij) (hlabels.ne hik) (hlabels.ne hjk)
      rw [abs_div, abs_of_pos hm, le_div_iff₀ hm]
      simpa using hmin
    obtain ⟨hβpos, hupos, hαpos⟩ :=
      TriHull.inTriStrict_fan_pos h.ccw.1 h.Q_in_ABC
    obtain ⟨hγpos, hvpos, _⟩ :=
      TriHull.inTriStrict_fan_pos h.ccw.2.1 h.Q_in_BCD
    have hδpos : 0 < sig (v h.Q) (v D) (v A) := by
      obtain ⟨qx, qy, qz, hqx, hqy, hqz, hqsum, hQeq⟩ := h.Q_in_ABC
      have hBDApos : 0 < sig (v B) (v D) (v A) := by
        calc
          0 < sig (v D) (v A) (v B) := h.ccw.2.2.2
          _ = sig (v A) (v B) (v D) := sig_rotate _ _ _
          _ = sig (v B) (v D) (v A) := sig_rotate _ _ _
      have hCDApos : 0 < sig (v C) (v D) (v A) := h.ccw.2.2.1
      rw [hQeq,
        sig_affine_fst (v A) (v B) (v C) (v D) (v A)
          qx qy qz hqsum]
      simp only [sig_eq13, mul_zero, zero_add]
      exact add_pos (mul_pos hqy hBDApos) (mul_pos hqz hCDApos)
    obtain ⟨hepos, hap_pos', hxpos'⟩ :=
      TriHull.inTriStrict_fan_pos hδpos h.Z_in_QDA
    have hxpos : 0 < sig (v h.Q) (v D) (v h.Z) := by
      simpa only [sig_rotate (v h.Z) (v h.Q) (v D)] using hxpos'
    have hap_pos : 0 < sig (v A) (v h.Q) (v h.Z) := by
      simpa only [sig_rotate (v h.Z) (v A) (v h.Q)] using hap_pos'
    have hACDpos : 0 < sig (v A) (v C) (v D) := by
      have hCDApos := h.ccw.2.2.1
      have heq :
          sig (v A) (v C) (v D) = sig (v C) (v D) (v A) := by
        simp only [sig]
        ring
      rw [heq]
      exact hCDApos
    have hαunit :
        1 ≤ sig (v h.Q) (v A) (v B) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 0 1 (by decide) (by decide) (by decide) hαpos
    have hβunit :
        1 ≤ sig (v h.Q) (v B) (v C) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 1 2 (by decide) (by decide) (by decide) hβpos
    have hγunit :
        1 ≤ sig (v h.Q) (v C) (v D) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 2 3 (by decide) (by decide) (by decide) hγpos
    have hδunit :
        1 ≤ sig (v h.Q) (v D) (v A) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 3 0 (by decide) (by decide) (by decide) hδpos
    have huunit :
        1 ≤ sig (v h.Q) (v C) (v A) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 2 0 (by decide) (by decide) (by decide) hupos
    have hvunit :
        1 ≤ sig (v h.Q) (v D) (v B) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 3 1 (by decide) (by decide) (by decide) hvpos
    have haunit :
        1 ≤ sig (v A) (v h.Q) (v h.Z) / minTri v := by
      simpa [labels] using
        unit_of_pos 0 4 7 (by decide) (by decide) (by decide) hap_pos
    have hxunit :
        1 ≤ sig (v h.Q) (v D) (v h.Z) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 3 7 (by decide) (by decide) (by decide) hxpos
    have heunit :
        1 ≤ sig (v h.Z) (v D) (v A) / minTri v := by
      simpa [labels] using
        unit_of_pos 7 3 0 (by decide) (by decide) (by decide) hepos
    have hwunit :
        1 ≤ |sig (v A) (v h.Z) (v C) / minTri v| := by
      simpa [labels] using
        abs_unit 0 7 2 (by decide) (by decide) (by decide)
    let qabSlots : Fin 5 → Fin 8 := ![4, 0, 1, 5, 6]
    have hqabSlots : Function.Injective qabSlots := by decide
    let qabLabels : Fin 5 → Fin 8 := fun i => labels (qabSlots i)
    have hqabLabels : Function.Injective qabLabels := by
      exact hlabels.comp hqabSlots
    have hαmain :
        4 + 2 * Real.sqrt 3 ≤
          sig (v h.Q) (v A) (v B) / minTri v := by
      simpa [qabLabels, qabSlots, labels] using
        TriHull.twoPointTriangle_normalized_lower_bound v qabLabels
          hqabLabels hm hαpos
          (by simpa [qabLabels, qabSlots, labels] using h.P_in_QAB)
          (by simpa [qabLabels, qabSlots, labels] using h.R_in_QAB)
    have hαtwo :
        F2 < sig (v h.Q) (v A) (v B) / minTri v := by
      norm_num [F2] at ⊢
      nlinarith [TriHull.sixty_nine_fortieths_lt_sqrt_three]
    have hACDunit :
        1 ≤ sig (v A) (v C) (v D) / minTri v := by
      simpa [labels] using
        unit_of_pos 0 2 3 (by decide) (by decide) (by decide) hACDpos
    let H : ℝ :=
      (sig (v A) (v B) (v C) + sig (v A) (v C) (v D)) / minTri v
    let α : ℝ := sig (v h.Q) (v A) (v B) / minTri v
    let β : ℝ := sig (v h.Q) (v B) (v C) / minTri v
    let γ : ℝ := sig (v h.Q) (v C) (v D) / minTri v
    let δ : ℝ := sig (v h.Q) (v D) (v A) / minTri v
    let u : ℝ := sig (v h.Q) (v C) (v A) / minTri v
    let qdb : ℝ := sig (v h.Q) (v D) (v B) / minTri v
    let a : ℝ := sig (v A) (v h.Q) (v h.Z) / minTri v
    let b : ℝ := sig (v h.Q) (v h.Z) (v B) / minTri v
    let c : ℝ := sig (v h.Z) (v A) (v B) / minTri v
    let x : ℝ := sig (v h.Q) (v D) (v h.Z) / minTri v
    let e : ℝ := sig (v h.Z) (v D) (v A) / minTri v
    let w : ℝ := sig (v A) (v h.Z) (v C) / minTri v
    have hdiagAC : u ≤ γ + δ - 1 := by
      have hdecomp :
          sig (v A) (v C) (v D) / minTri v = γ + δ - u := by
        dsimp [γ, δ, u]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      rw [hdecomp] at hACDunit
      linarith
    have hdirect : OrbitIIJ2Direct H := by
      refine
        { α := α
          β := β
          γ := γ
          δ := δ
          u := u
          v := qdb
          a := a
          b := b
          c := c
          x := x
          e := e
          w := w
          hull_eq := ?_
          α_unit := by simpa [α] using hαunit
          β_unit := by simpa [β] using hβunit
          γ_unit := by simpa [γ] using hγunit
          δ_unit := by simpa [δ] using hδunit
          u_unit := by simpa [u] using huunit
          v_unit := by simpa [qdb] using hvunit
          plucker := ?_
          alpha_two := by simpa [α] using hαtwo
          delta_split := ?_
          qab_split := ?_
          qdz_identity := ?_
          zda_identity := ?_
          azc_identity := ?_
          a_unit := by simpa [a] using haunit
          x_unit := by simpa [x] using hxunit
          e_unit := by simpa [e] using heunit
          w_unit := by simpa [w] using hwunit
          diagonal_AC := hdiagAC }
      · dsimp [H, α, β, γ, δ]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, β, γ, δ, u, qdb]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [δ, a, x, e]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, a, b, c]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, δ, qdb, a, b, x]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, δ, qdb, a, c, e]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, β, u, a, c, w]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
    refine Or.inr ⟨H, ?_, .orbit_II_j2 hdirect⟩
    dsimp [H, quadHullArea, oarea]
    field_simp [ne_of_gt hm]

/--
Geometric data for the opposite `3+1` branch.  The point `Q` is in the
`BCO` sector, and the other three points lie strictly in the opposite fan
triangle `QDA`.
-/
structure OppositeThreeOneGeometryCertificate
    (v : Fin 8 → Point) (A B C D : Fin 8) where
  Q : Fin 8
  P : Fin 8
  R : Fin 8
  S : Fin 8
  labels_injective : Function.Injective ![A, B, C, D, Q, P, R, S]
  ccw : CCWQuad (v A) (v B) (v C) (v D)
  Q_in_ABC : TriHull.InTriStrict (v Q) (v A) (v B) (v C)
  Q_in_BCD : TriHull.InTriStrict (v Q) (v B) (v C) (v D)
  P_in_QDA : TriHull.InTriStrict (v P) (v Q) (v D) (v A)
  R_in_QDA : TriHull.InTriStrict (v R) (v Q) (v D) (v A)
  S_in_QDA : TriHull.InTriStrict (v S) (v Q) (v D) (v A)

/-- The geometric opposite `3+1` placement constructs its normalized orbit. -/
theorem OppositeThreeOneGeometryCertificate.orbitCertificate
    {v : Fin 8 → Point} {A B C D : Fin 8}
    (h : OppositeThreeOneGeometryCertificate v A B C D) :
    OrbitCertificate v A B C D := by
  by_cases hmzero : minTri v = 0
  · exact Or.inl hmzero
  · have hm : 0 < minTri v :=
      lt_of_le_of_ne (minTri_nonneg v) (Ne.symm hmzero)
    let labels : Fin 8 → Fin 8 := ![A, B, C, D, h.Q, h.P, h.R, h.S]
    have hlabels : Function.Injective labels := by
      simpa [labels] using h.labels_injective
    have unit_of_pos (i j k : Fin 8)
        (hij : i ≠ j) (hik : i ≠ k) (hjk : j ≠ k)
        (hpos : 0 < sig (v (labels i)) (v (labels j)) (v (labels k))) :
        1 ≤ sig (v (labels i)) (v (labels j)) (v (labels k)) / minTri v := by
      have hmin := minTri_le_abs_sig_of_pairwise_ne v
        (hlabels.ne hij) (hlabels.ne hik) (hlabels.ne hjk)
      rw [abs_of_pos hpos] at hmin
      rw [le_div_iff₀ hm]
      simpa using hmin
    obtain ⟨hβpos, hupos, hαpos⟩ :=
      TriHull.inTriStrict_fan_pos h.ccw.1 h.Q_in_ABC
    obtain ⟨hγpos, hvpos, _⟩ :=
      TriHull.inTriStrict_fan_pos h.ccw.2.1 h.Q_in_BCD
    have hδpos : 0 < sig (v h.Q) (v D) (v A) := by
      obtain ⟨qx, qy, qz, hqx, hqy, hqz, hqsum, hQeq⟩ := h.Q_in_ABC
      have hBDApos : 0 < sig (v B) (v D) (v A) := by
        calc
          0 < sig (v D) (v A) (v B) := h.ccw.2.2.2
          _ = sig (v A) (v B) (v D) := sig_rotate _ _ _
          _ = sig (v B) (v D) (v A) := sig_rotate _ _ _
      have hCDApos : 0 < sig (v C) (v D) (v A) := h.ccw.2.2.1
      rw [hQeq,
        sig_affine_fst (v A) (v B) (v C) (v D) (v A)
          qx qy qz hqsum]
      simp only [sig_eq13, mul_zero, zero_add]
      exact add_pos (mul_pos hqy hBDApos) (mul_pos hqz hCDApos)
    have hαunit :
        1 ≤ sig (v h.Q) (v A) (v B) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 0 1 (by decide) (by decide) (by decide) hαpos
    have hβunit :
        1 ≤ sig (v h.Q) (v B) (v C) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 1 2 (by decide) (by decide) (by decide) hβpos
    have hγunit :
        1 ≤ sig (v h.Q) (v C) (v D) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 2 3 (by decide) (by decide) (by decide) hγpos
    have hδunit :
        1 ≤ sig (v h.Q) (v D) (v A) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 3 0 (by decide) (by decide) (by decide) hδpos
    have huunit :
        1 ≤ sig (v h.Q) (v C) (v A) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 2 0 (by decide) (by decide) (by decide) hupos
    have hvunit :
        1 ≤ sig (v h.Q) (v D) (v B) / minTri v := by
      simpa [labels] using
        unit_of_pos 4 3 1 (by decide) (by decide) (by decide) hvpos
    let qdaSlots : Fin 6 → Fin 8 := ![4, 3, 0, 5, 6, 7]
    have hqdaSlots : Function.Injective qdaSlots := by decide
    let qdaLabels : Fin 6 → Fin 8 := fun i => labels (qdaSlots i)
    have hqdaLabels : Function.Injective qdaLabels := by
      exact hlabels.comp hqdaSlots
    have hδthree :
        (17 : ℝ) / 2 ≤ sig (v h.Q) (v D) (v A) / minTri v := by
      simpa [qdaLabels, qdaSlots, labels] using
        TriHull.threePointTriangle_normalized_lower_bound_unconditional
          v qdaLabels hqdaLabels hm hδpos
          (by simpa [qdaLabels, qdaSlots, labels] using h.P_in_QDA)
          (by simpa [qdaLabels, qdaSlots, labels] using h.R_in_QDA)
          (by simpa [qdaLabels, qdaSlots, labels] using h.S_in_QDA)
    let H : ℝ :=
      (sig (v A) (v B) (v C) + sig (v A) (v C) (v D)) / minTri v
    let α : ℝ := sig (v h.Q) (v A) (v B) / minTri v
    let β : ℝ := sig (v h.Q) (v B) (v C) / minTri v
    let γ : ℝ := sig (v h.Q) (v C) (v D) / minTri v
    let δ : ℝ := sig (v h.Q) (v D) (v A) / minTri v
    let u : ℝ := sig (v h.Q) (v C) (v A) / minTri v
    let qdb : ℝ := sig (v h.Q) (v D) (v B) / minTri v
    let hfan : PositivePluckerFan H := by
      refine
        { α := α
          β := β
          γ := γ
          δ := δ
          u := u
          v := qdb
          hull_eq := ?_
          α_unit := by simpa [α] using hαunit
          β_unit := by simpa [β] using hβunit
          γ_unit := by simpa [γ] using hγunit
          δ_unit := by simpa [δ] using hδunit
          u_unit := by simpa [u] using huunit
          v_unit := by simpa [qdb] using hvunit
          plucker := ?_ }
      · dsimp [H, α, β, γ, δ]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
      · dsimp [α, β, γ, δ, u, qdb]
        field_simp [ne_of_gt hm]
        simp only [sig]
        ring
    refine Or.inr ⟨H, ?_, .opposite_three_one hfan ?_⟩
    · dsimp [H, quadHullArea, oarea]
      field_simp [ne_of_gt hm]
    · simpa [hfan, δ] using hδthree

/-- QuadHull8 with the balanced-diagonal certificate as its entry datum. -/
theorem quadHull8_balanced
    (v : Fin 8 → Point) (A B C D : Fin 8)
    (hunit : quadHullArea (v A) (v B) (v C) (v D) = 1)
    (hbalanced : BalancedDiagonalCertificate v A B C D) :
    minTri v / 2 ≤ (5 : ℝ) / 63 :=
  quadHull8_unconditional v A B C D hunit
    hbalanced.orbitCertificate

end Heilbronn8.QuadHull
